"""add chat room

Revision ID: 6f24887cfce4
Revises: 
Create Date: 2021-07-12 17:14:08.272327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f24887cfce4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatroom',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('creator', postgresql.UUID(), nullable=True),
    sa.Column('members', sa.ARRAY(postgresql.UUID()), nullable=True),
    sa.Column('chat_storage_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_storage_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatroom')
    # ### end Alembic commands ###
